<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Home extends Model
{
    use HasFactory;

    public function getRouteKeyName()
    {
        return "slug"; // TODO: Change the autogenerated stub
    }
}
